### ISSUE TITLE
Evaluate Paralus

### ISSUE THREAD

**Issue by ralgozino** [sighupio/fury-kubernetes-auth#14]
Paralus (https://www.paralus.io/) seems to be a good fit for the auth module.

> Paralus is a free, open source tool that enables controlled, audited access to Kubernetes infrastructure. It comes with just-in-time service account creation and user-level credential management that integrates with your RBAC and SSO. Ships as a GUI, API, and CLI.

Evaluate the tool and understand if it could be added as a package of this module and how it sits against the other packages (Dex, Pomerium, Gangway).

**Comment by jnardiello** [comment]
Please, keep in mind that any addition to this module (as for any new component of Fury) is going to become a dependency for us - so it's important to carefully consider who develops the component, what happens if they deprecate it, and what is their role in terms of partnerships with SIGHUP.

Paralus, behind the OSS project is developed by https://rafay.co/ FYI

In general, we must maintain any component that we introduce in the distro.
